"""empty message

Revision ID: 02b508e869ed
Revises: f5d7f4ec0acf
Create Date: 2020-09-29 13:42:49.671559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02b508e869ed'
down_revision = 'f5d7f4ec0acf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cash_db', sa.Column('EUR', sa.Integer(), nullable=True))
    op.add_column('cash_db', sa.Column('RUB', sa.Integer(), nullable=True))
    op.add_column('cash_db', sa.Column('USD', sa.Integer(), nullable=True))
    op.drop_column('cash_db', 'euro')
    op.drop_column('cash_db', 'usd')
    op.drop_column('cash_db', 'rub')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cash_db', sa.Column('rub', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('cash_db', sa.Column('usd', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('cash_db', sa.Column('euro', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('cash_db', 'USD')
    op.drop_column('cash_db', 'RUB')
    op.drop_column('cash_db', 'EUR')
    # ### end Alembic commands ###
