"""empty message

Revision ID: 040c201e2683
Revises: 511b9bfdf752
Create Date: 2020-10-13 17:23:11.524714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '040c201e2683'
down_revision = '511b9bfdf752'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_db',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.Column('minsum', sa.Integer(), nullable=True),
    sa.Column('reportfrequency', sa.Integer(), nullable=True),
    sa.Column('reportday', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('userid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_db')
    # ### end Alembic commands ###
