"""empty message

Revision ID: 1b5fc3c225da
Revises: 040c201e2683
Create Date: 2020-10-13 17:27:38.626864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b5fc3c225da'
down_revision = '040c201e2683'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_db', sa.Column('currency', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_db', 'currency')
    # ### end Alembic commands ###
