"""empty message

Revision ID: 3081fbae784d
Revises: 89a0004b4821
Create Date: 2020-10-19 15:07:17.253479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3081fbae784d'
down_revision = '89a0004b4821'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_db', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_db', sa.Column('password', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
