"""empty message

Revision ID: 3c8495dbf54f
Revises: 1b0b2411d23b
Create Date: 2020-09-23 12:01:55.939086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c8495dbf54f'
down_revision = '1b0b2411d23b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('portfolio_db', 'userid', new_column_name='id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('portfolio_db', 'id', new_column_name='userid')
    # ### end Alembic commands ###
