"""empty message

Revision ID: 511b9bfdf752
Revises: 02b508e869ed
Create Date: 2020-09-30 14:43:01.035268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '511b9bfdf752'
down_revision = '02b508e869ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_db',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('classname', sa.String(length=64), nullable=True),
    sa.Column('fraction', sa.Integer(), nullable=True),
    sa.Column('diapason', sa.Integer(), nullable=True),
    sa.Column('activeticker', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ticker_db', sa.Column('classname', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticker_db', 'classname')
    op.drop_table('class_db')
    # ### end Alembic commands ###
