"""empty message

Revision ID: 93187099b35c
Revises: 3081fbae784d
Create Date: 2020-10-19 15:09:12.398427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93187099b35c'
down_revision = '3081fbae784d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_db', sa.Column('hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_db', 'hash')
    # ### end Alembic commands ###
